/**
 * Generates security headers, including a CSP with per-script hashes.
 *
 * Because the site loads nothing from a third party, the policy can be
 * genuinely strict: no 'unsafe-inline' for scripts, no external origins at
 * all. Our own inline scripts (the pre-paint theme resolver, the nav toggle,
 * the hero rotator) are allowed by SHA-256 hash instead.
 *
 * Writes:
 *   <served dir>/_headers — Netlify, Cloudflare Pages and Cloudflare Workers
 *   vercel.json      — Vercel (rewritten in place, committed)
 *   deploy/headers.conf — nginx, included by the Dockerfile image
 *
 * Runs as part of `npm run build`, so the hashes can never go stale.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

const DIST = path.join(process.cwd(), 'dist');

/**
 * The directory Astro actually emitted, which is not always `dist`.
 *
 * A server adapter splits the build into `dist/client` and `dist/server`, and
 * the host serves `dist/client`. A first Cloudflare deploy hit exactly this:
 * `wrangler deploy` ran `astro add cloudflare` on the build machine, the
 * adapter moved the output, and `_headers` was written one directory above
 * what was being served — so the site went live with no CSP, no HSTS and no
 * frame protection at all, while the build still printed a tick.
 *
 * Detect it rather than assume it. `_headers` is inert if it lands in the
 * wrong place, and inert in a way nothing in the build would catch.
 */
async function servedDir() {
  try {
    const { stat } = await import('node:fs/promises');
    const client = path.join(DIST, 'client');
    if ((await stat(path.join(client, 'index.html'))).isFile()) return client;
  } catch {
    /* no adapter split — the plain dist/ layout */
  }
  return DIST;
}

const SERVED = await servedDir();

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else if (e.name.endsWith('.html')) out.push(p);
  }
  return out;
}

// --- Collect inline script hashes ----------------------------------------
const hashes = new Set();
for (const file of await walk(SERVED)) {
  const src = await readFile(file, 'utf8');
  for (const m of src.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
    const body = m[1];
    if (!body.trim()) continue;
    // JSON-LD is data, not executable script, and needs no hash.
    if (/type\s*=\s*["']application\/ld\+json["']/i.test(m[0])) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

const scriptSrc = ["'self'", ...[...hashes].sort()].join(' ');

const CSP = [
  `default-src 'self'`,
  `script-src ${scriptSrc}`,
  // Tailwind emits inline style attributes; styles load from our origin only.
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data:`,
  `font-src 'self'`,
  // No XHR/fetch anywhere: the site has no API to call.
  `connect-src 'self'`,
  `frame-ancestors 'none'`,
  `form-action 'none'`,
  `base-uri 'self'`,
  `object-src 'none'`,
  `upgrade-insecure-requests`,
].join('; ');

const HEADERS = {
  'Content-Security-Policy': CSP,
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'X-Frame-Options': 'DENY',
  // Deny every powerful feature: the site uses none of them.
  'Permissions-Policy':
    'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

// --- Netlify / Cloudflare Pages ------------------------------------------
const netlify = [
  '# Generated by scripts/gen-headers.mjs — do not edit by hand.',
  '/*',
  ...Object.entries(HEADERS).map(([k, v]) => `  ${k}: ${v}`),
  '',
  '# Fingerprinted assets are immutable.',
  '/_astro/*',
  '  Cache-Control: public, max-age=31536000, immutable',
  '',
  '/fonts/*',
  '  Cache-Control: public, max-age=31536000, immutable',
  '',
  '/og/*',
  '  Cache-Control: public, max-age=604800',
  '',
].join('\n');
await writeFile(path.join(SERVED, '_headers'), netlify);

// --- Vercel ---------------------------------------------------------------
const vercel = {
  $schema: 'https://openapi.vercel.sh/vercel.json',
  buildCommand: 'npm run build',
  outputDirectory: 'dist',
  cleanUrls: true,
  trailingSlash: false,
  headers: [
    {
      source: '/(.*)',
      headers: Object.entries(HEADERS).map(([key, value]) => ({ key, value })),
    },
    {
      source: '/_astro/(.*)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
    {
      source: '/fonts/(.*)',
      headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
    },
  ],
};
await writeFile(path.join(process.cwd(), 'vercel.json'), JSON.stringify(vercel, null, 2) + '\n');

// --- nginx ---------------------------------------------------------------
await mkdir(path.join(process.cwd(), 'deploy'), { recursive: true });
const nginx = [
  '# Generated by scripts/gen-headers.mjs — do not edit by hand.',
  ...Object.entries(HEADERS).map(([k, v]) => `add_header ${k} "${v}" always;`),
  '',
].join('\n');
await writeFile(path.join(process.cwd(), 'deploy', 'headers.conf'), nginx);

console.log(
  `✓ security headers written (CSP allows ${hashes.size} inline script hash${hashes.size === 1 ? '' : 'es'}, no 'unsafe-inline')`
);
